indent = 4
margin = 88
whitespace_ops_in_indices = false
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = false
always_use_return = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = true
indent_submodule = true
separate_kwargs_with_semicolon = true
format_markdown = true

align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
